project:
  type: website
  output-dir: docs

website:
  title: "Jacob Jannicelli"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: experience.qmd
        text: Experience
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
